### ISSUE TITLE
你好，这个应用如何使用呀，为啥一直访问不了？

### ISSUE THREAD

**Issue by sunnycn2013** [medz/thinksns-app-old-w3g#1]
你好，我在本地尝试了你们的开源框架 `https://github.com/medz/thinksns`, 我想使用这个3G的应用，我下载以后把thinksns-app-old-w3g 放进apps/目录下，然后手动配置了appinfo，去thinksns后台安装应用，安装完毕后使用 `http://caibei.com/index.php?app=w3g&mod=Index&act=index` 依旧打不开

**Comment by medz** [comment]
该项目已经停止维护，请使用新版本 https://github.com/zhiyicx/thinksns-plus h5 是开源的
在 2017年6月23日，09:39，千玑 <notifications@github.com<mailto:notifications@github.com>> 写道：


你好，我在本地尝试了你们的开源框架 https://github.com/medz/thinksns, 我想使用这个3G的应用，我下载以后把thinksns-app-old-w3g 放进apps/目录下，然后手动配置了appinfo，去thinksns后台安装应用，安装完毕后使用 http://caibei.com/index.php?app=w3g&mod=Index&act=index 依旧打不开
